# Generated by Django 3.0.3 on 2020-05-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.URLField(blank=True),
        ),
    ]
