# Generated by Django 3.0.3 on 2020-05-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_course_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
