# Generated by Django 3.0.3 on 2020-05-11 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20200510_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='link',
            new_name='github_link',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='website_link',
            field=models.URLField(blank=True),
        ),
    ]
