# Generated by Django 3.0.3 on 2020-05-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20200511_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('percent', models.IntegerField()),
                ('fa_icon', models.URLField(blank=True)),
                ('rank', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='portfolio',
            name='tags',
            field=models.ManyToManyField(to='portfolio.Technology'),
        ),
    ]
