# Generated by Django 3.0.3 on 2020-05-16 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20200517_0234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technology',
            old_name='fa_icon',
            new_name='icon',
        ),
    ]
