# Generated by Django 3.0.6 on 2020-05-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20200517_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='tags',
            field=models.ManyToManyField(blank=True, to='portfolio.Technology'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='icon',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
