# Generated by Django 3.0.3 on 2020-05-18 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20200517_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
