# Generated by Django 3.0.6 on 2020-05-26 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_technology_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='ongoing',
            field=models.BooleanField(default=True),
        ),
    ]
