# Generated by Django 3.0.3 on 2020-06-09 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_portfolio_ongoing'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='show_to_home',
            field=models.BooleanField(default=True),
        ),
    ]
