# Generated by Django 3.0.3 on 2020-07-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_auto_20200726_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='show',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='technology',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
