# Generated by Django 3.0.3 on 2020-07-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_auto_20200726_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='from_scratch',
            field=models.BooleanField(default=True),
        ),
    ]
